name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    environment: production   # Enables GitHub manual approval

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: ./keypair
      - run: terraform apply -auto-approve
        working-directory: ./keypair

      - name: Upload Private Key
        uses: actions/upload-artifact@v4
        with:
          name: private-key
          # Terraform creates the file in the working-directoryJ
          path: ./keypair/*.pem
          retention-days: 1
