name: Terraform Plan

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      # ---------------------------
      # Configure AWS via OIDC
      # ---------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}

      # ---------------------------
      # Setup Terraform
      # ---------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: ./keypair
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./keypair
        run: terraform init

      - name: Terraform Validate
        working-directory: ./keypair
        run: terraform validate

      # ---------------------------
      # TFLint (Static Analysis)
      # ---------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      # ---------------------------
      # Checkov (Security Scan)
      # ---------------------------
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: cli
          quiet: true
          soft_fail: false   # Fail pipeline if security issues found

      # ---------------------------
      # Terraform Plan
      # ---------------------------
      - name: Terraform Plan
        working-directory: ./keypair
        run: terraform plan -out=tfplan

      # NEW STEP: Convert binary plan to human-readable text
      - name: Create Readable Plan Preview
        working-directory: ./keypair
        run: terraform show -no-color tfplan > plan_preview.txt

      # Upload both the binary (for the machine) and text (for you)
      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ./keypair/tfplan
            ./keypair/plan_preview.txt
          retention-days: 5
